##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

#TODO: fix
# windowrule = suppressevent maximize, class:.* # You'll probably like this.

#-------------------------------------------------------


# nwg-look
windowrule {
    name = nwg-look
    match:class = (.*nwg-look.*)
    float = true
    center = true
    pin = false
    size = 600 500
}

# blueman-manager
windowrule {
    name = blueman-manager
    match:class = (.*blueman-manager.*)
    float = true
    pin = true
    size = 800 500
    move = 1220 50
}

# thunar

# gnome-calculator
windowrule {
    name = gnome-calculator
    match:class = (.*org.gnome.Calculator.*)
    float = true
    center = true
    pin = false
    size = 400 500
}

# waypaper
windowrule {
    name = waypaper 
    match:class = (.*waypaper.*)
    float = true
    center = true
    pin = true
    size = 800 800
}

# Picture-in-Picture
windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}

# common modals
# TODO: FIX REQUIRED
# windowrule = float,title:^(Open)$
#
# windowrule= float,title:^(Choose Files)$
# windowrule= float,class:^(brave)$, title:.*wants to open.* # brave choose files dialog
# windowrule= float, class:^(brave)$, title:.*open.* # brave open file dialog
#
#
# windowrule= float,title:^(Save As)$ # firefox
# windowrule = float,title:^(Save File) # brave
# windowrule= float,title:^(Confirm to replace files)$
# windowrule= float,title:^(File Operation Progress)$

# windowrule= float,class:^(xdg-desktop-portal-hyprland)$
#
#
# # kde team 
# windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
# windowrule = noanim, class:^(xwaylandvideobridge)$
# windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
# windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
# windowrule = noblur, class:^(xwaylandvideobridge)$
# windowrule = nofocus, class:^(xwaylandvideobridge)$
#
#
# windowrule = opacity 0.75 $& 0.75 $& 1,class:^(kitty)$
# windowrule = opacity 0.80 $& 0.80 $& 1,class:^(thunar)$
#

