
# Theme
include tokyo-night-storm.conf

# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
bold_italic_font JetBrainsMono Nerd Font Bold Italic 
italic_font      JetBrainsMono Nerd Font Italic

# Window
# window_padding_width 5

# Mouse
shell_integration no-cursor
mouse_hide -1.0


# Cursor
cursor                  #ffffff
cursor_shape block
cursor_blink_interval 0
cursor_text_color       #0a0e1a
url_color               #4a90d9


# key maps
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window
