# Tokyo Night Storm Theme

foreground               #c0caf5
background               #1a1b26
selection_foreground     #1a1b26
selection_background     #7aa2f7

cursor                   #ff9e64
cursor_text_color       #1a1b26
url_color                #7dcfff

active_tab_foreground    #c0caf5
active_tab_background    #24283b
inactive_tab_foreground  #565f89
inactive_tab_background  #1a1b26

active_border_color      #7aa2f7
inactive_border_color    #1a1b26

color0   #15161e
color8   #414868

color1   #f7768e
color9   #ff9e64

color2   #9ece6a
color10  #73daca

color3   #e0af68
color11  #ff9e64

color4   #7aa2f7
color12  #7dcfff

color5   #bb9af7
color13  #b4f9f8

color6   #7dcfff
color14  #2ac3de

color7   #a9b1d6
color15  #c0caf5